### ISSUE TITLE
Crash near Averheim or Grenzstadt

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOW_Core#128]
From discord, the user [flavahbeast](https://discord.com/channels/702088927380635678/739460631224123443/888673487030452224) reports in the later game, crashes, particularly near Averheim or Grenzstadt.  No crash files for this have been provided.

As crashes are evident in all regions, I have not specifically spent time at this location.  It may be that in time this is discovered a duplicate of an existing issue.
[DxDiag_of_flavahbeast.txt](https://github.com/WarhammerTheOldWorld/TOW_Core/files/7190558/DxDiag_of_flavahbeast.txt)

**Comment by fogbug** [comment]
Here's a sample set of activities I did on the Moddb branch that ended in a crash in that region: I haven't been able to trigger one consistently though

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours (All activities that sometimes cause crashes on the campaign map for me)
- Ran to Grenzstadt, entered and exited the trade screen a few times, waited in town for a bit
- Ran back towards Averheim, let a group of bandits attack me on the way, fought the battle on the battle map and lost
- After the bandit party was wiped out by a lord and I was freed I ran back to Averheim
- At Averheim I waited in town and crashed after a few in-game hours

**Heres the full log file from that session**:
https://cdn.discordapp.com/attachments/519542011297136657/888955676141961246/rgl_log_14284.txt

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours 
- Ran to Grenzstadt, entered and exited the trade screen a few times, waited in town for a bit
- Ran back towards Averheim, let a group of bandits attack me on the way, tried to fight the battle on the battle map but crashed as soon as I clicked the 'Attack' dialogue option

**Full log from that session**:
https://cdn.discordapp.com/attachments/519542011297136657/888955959182000168/rgl_log_10348.txt

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours
- Ran to Grenzstadt, entered and exited the trade screen a few times, waited in town and crashed after a couple in-game hours

**Full log from that session**:
https://cdn.discordapp.com/attachments/519542011297136657/888956476952047666/rgl_log_12196.txt

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours
- Ran to Grenzstadt, entered and exited the trade screen a few times, crashed while exiting the fourth time

**Full log from that session**
https://cdn.discordapp.com/attachments/519542011297136657/888956664470994954/rgl_log_13708.txt

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours
- Tried to run to Grenzstadt but crashed on the way there
- 
**Full log from that session**
https://cdn.discordapp.com/attachments/519542011297136657/888958338279276544/rgl_log_13508.txt

- Started a level 1 Empire character
- Ran to Averheim, entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, forgot to wait in town this time
- Ran to Grenzstadt, entered and exited the trade screen a few times, crashed while exiting the fourth time

**Full log from that session**
https://cdn.discordapp.com/attachments/519542011297136657/888960803951218698/rgl_log_3856.txt

- I noticed that my total system memory usage while idle in Averheim had increased from 6.9/16gb to 7.7/16gb, I rebooted to see if that made a difference

//**REBOOT**//



- Started a level 1 Empire character
- Ran to Averheim
- idle memory usage is back down to 6.9gb
- entered and exited the Trade screen a few times, zoomed the camera in and out, panned the camera around, waited in town for a few hours
- Ran to Grenzstadt, entered and exited the trade screen a few times, waited in town for a bit
- Ran back towards Averheim, let a group of bandits attack me on the way, fought the battle on the battle map and lost
- Bandits freed me for a bribe and I ran back to Averheim
- At Averheim I waited in town for several days without crashing, I left and wandered around a little while panning the camera, then closed the client manually

**Full log from that session**
https://cdn.discordapp.com/attachments/519542011297136657/888964717773733988/rgl_log_11604.txt

~~I think Nvidia Experience may be the culprit: over time, possibly due to alt tabbing, it opens up multiple 'Nvidia Container' processes that eat up RAM. I didn't think it was an issue for Bannerlord, but it caused a lot of headaches in Warband:~~

https://www.reddit.com/r/mountandblade/comments/kg6qm1/moving_the_mouse_causes_lag/gtg67e5/
https://forums.taleworlds.com/index.php?threads/game-with-current-update-is-unplayable-lags-and-stutter-nonstop.442142/#post-9681507

It might be something that only affects people with older RAM (I'm still using DDR3). I'll be upgrading my system later this week when parts arrive so I wanted to test this now since people with older systems will probably keep trying to play the game (and other than this the game and mod run fine for me)

(I have Better Exception Windows installed but unfortunately it doesn't work very often, usually I get the generic TW error window)

**Comment by fogbug** [comment]
After playing the Moddb branch for a while with Nvidia's GeForce Experience disabled I'm still seeing crashes with the same regularity, so it's not that

**Comment by martkartasev** [comment]
https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/915793761c8cf083900475baaddd3475ec5107c4
https://github.com/WarhammerTheOldWorld/TOW_CoreAssets/commit/b61d1dc45f7959ded4239d3a844ca5cde0ea09e4
