### ISSUE TITLE
Graveyard mission (new location)

### ISSUE THREAD

**Issue by Badulundabad** [TheOldRealms/TOW_Core#237]
We need graveyard location for mission of undead raising.
I've created campaign behavior for it, but i need this location to continue.

**Comment by Badulundabad** [comment]
Player should be limited to raise undead, so i suggest "dead people" like resource that every town has, highly likely it should be hidden from player eyes

**Comment by Badulundabad** [comment]
If idea above is ok then we can mark graves with "grave" tag according amount of dead people. Grave gets glowing contour if player-necromancer places its summoning ability crosshair on the grave.
![image](https://user-images.githubusercontent.com/62873054/156917675-8658e0d2-fa68-4559-82e7-d26301814543.png)

**Comment by Badulundabad** [comment]
Or we could add additional summoning spell with self crosshair, so player can use it in graveyard mission without aiming graves.

**Comment by hunharibo** [comment]
you are overthinking this. Why do we even need a campaignbehaviour? We just need a mission to be launched from the town gamemenu that puts the player against 9-10 enemy peasants. Since graveyard menu option is already only available to players with the necromancer tag, we can be sure that they can raise dead via abiliy system already. No need for any extra mechanics IMO.
Graveyard scene is done (pending navmesh?) its in Environment.

**Comment by hunharibo** [comment]
You are right in the sense that we should limit other than raise dead spells in this mission. Killing all the enemy with a single wind of death would be just cheating 😆

**Comment by Badulundabad** [comment]
like library and raise undead(previous) stuff works with help of campaign behavior. Actually i can use current version of raise undead

**Comment by Badulundabad** [comment]
for example, it would be strange the player raises more dead than graves we have. So we need limit that i think

**Comment by Badulundabad** [comment]
we can make it easier for beginning, but anyway i would like to have much interesting version eventually, if you don't mind

**Comment by Z3rca** [comment]
> you are overthinking this. Why do we even need a campaignbehaviour? We just need a mission to be launched from the town gamemenu that puts the player against 9-10 enemy peasants. Since graveyard menu option is already only available to players with the necromancer tag, we can be sure that they can raise dead via abiliy system already. No need for any extra mechanics IMO. Graveyard scene is done (pending navmesh?) its in Environment.

I agree, in general, we still have to make use a lot of text-based interaction. This scene in my opinion should either be just a fight or used for some kind of "bandit camp raid" where the player has to clean a graveyard of zombies or something like that. 


> for example, it would be strange the player raises more dead than graves we have. So we need limit that i think

If the upcoming workflow is followed for the environment people, there is still a lot of backdrops so it is believable that you get more corpses from the graveyard than graves available. 


> You are right in the sense that we should limit other than raise dead spells in this mission. Killing all the enemy with a single wind of death would be just cheating 😆

Since the environment is then also bound by design to certain sizes, it also eases our job to define restrictions.  the extremely big spells or whatsoever have to be restricted for this sort of mission.
